
[Variables]

;--- IMPORTANT
; -- Please go to https://www.whatismybrowser.com/detect/what-is-my-user-agent
;-   Then copy the User Agent and paste it below.

MyUserAgent = Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

; --- # CurrencyPair URLs #  ---
; find the three-letter codes for the currencies you want to display 
;  and enter them below.

PairName1=USD / Euro
CurrencyPair1=EURUSD

PairName2=Euro / GBP
CurrencyPair2=GBPEUR

PairName3=USD / GBP
CurrencyPair3=GBPUSD

PairName4=JPY / USD
CurrencyPair4=USDJPY

PairName5=USD / AUD
CurrencyPair5=AUDUSD

PairName6=Euro / CAD 
CurrencyPair6=CADEUR

;---------------------------------





