
[Variables]

; --- # CurrencyPair URLs #  ---
; find the three-letter codes for the currencies you want to display 
;  and enter them below.

PairName1=USD / Euro
CurrencyPair1=EURUSD

PairName2=Euro / GBP
CurrencyPair2=GBPEUR

PairName3=USD / GBP
CurrencyPair3=GBPUSD

PairName4=JPY / USD
CurrencyPair4=USDJPY

PairName5=USD / AUD
CurrencyPair5=AUDUSD

PairName6=Euro / CAD 
CurrencyPair6=CADEUR

;---------------------------------





